### ISSUE TITLE
`Error: Invalid argument` thrown when using `SWIG_NAPI_Callback` synchronously

### ISSUE THREAD

**Issue by mateusz-plociennik** [mmomtchev/swig-napi-example-project#163]
I have the following `UsbNotifier` class that I am wrapping using [swig_napi_callback.i](https://github.com/mmomtchev/swig-napi-example-project/blob/main/src/swig_napi_callback.i) template:
```cpp
class UsbNotifier
{
	using DeviceCallback = std::function<void(std::shared_ptr<BMD::USB::IUSBDevice> usbDevice)>;

public:
	explicit UsbNotifier(const std::vector<uint16_t>& supportedProducts = {});
	~UsbNotifier() override;

	void setCallbacks(DeviceCallback onDeviceAdded, DeviceCallback onDeviceRemoved);
	bool init();
};
```

The issue I am facing is that synchronous callback fails. It works all fine when `DeviceCallback` is called asynchronously.

The relevant extract of the generated `rpcJAVASCRIPT_wrap.cxx` (copy of `swig_napi_callback.i`):
```cpp
  template <typename RET, typename ...ARGS>
  std::function<RET(ARGS...)> SWIG_NAPI_Callback(
      Napi::Value js_callback,
      std::function<void(Napi::Env, std::vector<napi_value> &, ARGS...)> tmaps_in,
      std::function<RET(Napi::Env, Napi::Value)> tmap_out
    ) {
      return SWIG_NAPI_Callback(js_callback, tmaps_in, tmap_out,
        [](Napi::Env env, Napi::Function js_callback, const std::vector<napi_value> &js_args){
          return js_callback.Call(env.Undefined(), js_args); // <- line 1391
      });
    }

  template <typename RET, typename ...ARGS>
  std::function<RET(ARGS...)> SWIG_NAPI_Callback(
      Napi::Value js_callback,
      std::function<void(Napi::Env, std::vector<napi_value> &, ARGS...)> tmaps_in,
      std::function<RET(Napi::Env, Napi::Value)> tmap_out,
      std::function<Napi::Value(Napi::Env, Napi::Function, const std::vector<napi_value> &)> call
    ) {
    Napi::Env env{js_callback.Env()};
    std::shared_ptr<Napi::ThreadSafeFunction> tsfn{new Napi::ThreadSafeFunction(Napi::ThreadSafeFunction::New(env,
      js_callback.As<Napi::Function>(),
      Napi::Object::New(env),
      "SWIG_callback_task",
      0,
      1
    )), [](Napi::ThreadSafeFunction *t){
      t->Release();
      delete t;
    }};

    // Here we are in the main V8 thread
    auto main_thread_id = std::this_thread::get_id();

    // $1 is what we pass to the C++ function -> it is a C++ wrapper
    // around the JS callback
    return [tsfn, js_callback, main_thread_id, tmaps_in, tmap_out, call](ARGS &&...args) -> RET {
      // Here we are called by the C++ code - we might be in a the main thread (synchronous call)
      // or a background thread (asynchronous call)
      auto worker_thread_id = std::this_thread::get_id();
      typename std::conditional<std::is_void_v<RET>, int, RET>::type c_ret;
      std::mutex m;
      std::condition_variable cv;
      bool ready = false;
      std::optional<std::string> error;

      // This is the actual trampoline that allows call into JS
      auto do_call = [&c_ret, &m, &cv, &ready, &error, tsfn, main_thread_id, worker_thread_id,
        tmaps_in, tmap_out, call, &args...]
        (Napi::Env env, Napi::Function js_fn) {
        // Here we are back in the main V8 thread, potentially from an async context
        Napi::HandleScope store{env};

        // Convert the C++ arguments to JS
        // ($typemap with arguments is currently an undocumented
        // but very useful SWIG feature that is not specific to SWIG JSE)
        std::vector<napi_value> js_args{sizeof...(args)};
        tmaps_in(env, js_args, args...);

        // Call the JS callback
        try {
          Napi::Value js_ret = call(env, js_fn, js_args); // <- line 1444

          // You don't need this part if you are not going to support async functions
#ifdef ASYNC_CALLBACK_SUPPORT
          // Handle the Promise in case the function was async
          if (js_ret.IsPromise()) {
            if (main_thread_id == worker_thread_id) {
              throw std::runtime_error{"Can't resolve a Promise when called synchronously"};
            }
            napi_value on_resolve = Napi::Function::New(env, [env, tmap_out, &c_ret, &m, &cv, &ready, &error]
                (const Napi::CallbackInfo &info) {
                Napi::HandleScope store{env};
                // Handle the JS return value
                try {
                  if constexpr (!std::is_void_v<RET>) {
                    c_ret = tmap_out(env, info[0]);
                  }
                } catch (const std::exception &e) {
                  error = e.what();
                }

                // Unblock the C++ thread
                std::unique_lock<std::mutex> lock{m};
                ready = true;
                lock.unlock();
                cv.notify_one();
              });
            napi_value on_reject = Napi::Function::New(env, [env, &c_ret, &m, &cv, &ready, &error]
                (const Napi::CallbackInfo &info) {
                Napi::HandleScope store{env};
                // Handle exceptions
                error = info[0].ToString();

                // Unblock the C++ thread
                std::unique_lock<std::mutex> lock{m};
                ready = true;
                lock.unlock();
                cv.notify_one();
              });
            js_ret.ToObject().Get("then").As<Napi::Function>().Call(js_ret, 1, &on_resolve);
            js_ret.ToObject().Get("catch").As<Napi::Function>().Call(js_ret, 1, &on_reject);
            return;
          }
#endif

          // Handle the JS return value
          if constexpr (!std::is_void_v<RET>) {
            c_ret = tmap_out(env, js_ret);
          }
        } catch (const std::exception &err) {
          // Handle exceptions
          error = err.what();
        }

        // Unblock the C++ thread
        std::unique_lock<std::mutex> lock{m};
        ready = true;
        lock.unlock();
        cv.notify_one();
      };

      // Are we in the thread pool background thread (V8 is not accessible) or not?
      // (this is what allows this typemap to work in both sync and async mode)
      if (worker_thread_id == main_thread_id) {
        // Synchronous call
        // (the js_callback Local reference is still valid -> it is on the stack)
        do_call(js_callback.Env(), js_callback.As<Napi::Function>()); // <- line 1510
      } else {
        // Asynchronous call
        // (js_callback is now a dangling Local reference)
        tsfn->BlockingCall(do_call);
      }

      // This is a barrier
      std::unique_lock<std::mutex> lock{m};
      cv.wait(lock, [&ready]{ return ready; });

      if (error) throw std::runtime_error{*error};
      if constexpr (!std::is_void_v<RET>) {
        return c_ret;
      }
    };
  }
```

The call stack, where `napi_call_function() != napi_ok`, that causes the code to throw: 
```
#0  0x00007ffff7cae4a1 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00007ffff4590165 in Napi::Function::Call (this=0x7fffffff8178, recv=0x56cd2f0, argc=1, args=0x5a66540) at /home/build/build/bmd-eng-ub_d0aV/project/BlackmagicTools/AppiumDriver/node_modules/node-addon-api/napi-inl.h:2676
#2  0x00007ffff4590e4e in Napi::Function::Call (this=0x7fffffff8178, recv=0x56cd2f0, args=std::vector of length 1, capacity 1 = {...}) at /home/build/build/bmd-eng-ub_d0aV/project/BlackmagicTools/AppiumDriver/node_modules/node-addon-api/napi-inl.h:2646
#3  0x00007ffff45b17b6 in SWIG_NAPI_Callback<void, std::shared_ptr<BMD::USB::IUSBDevice> >(Napi::Value, std::function<void (Napi::Env, std::vector<napi_value__*, std::allocator<napi_value__*> >&, std::shared_ptr<BMD::USB::IUSBDevice>)>, std::function<void (Napi::Env, Napi::Value)>)::{lambda(Napi::Env, Napi::Function, std::vector<napi_value__*, std::allocator<napi_value__*> > const&)#1}::operator()(Napi::Env, Napi::Function, std::vector<napi_value__*, std::allocator<napi_value__*> > const&) const (this=0x7fffffff8650, env=..., js_callback=..., js_args=std::vector of length 1, capacity 1 = {...})
    at CMakeFiles/rpc.dir/rpcJAVASCRIPT_wrap.cxx:1391
#4  0x00007ffff45b1746 in std::__invoke_impl<Napi::Value, SWIG_NAPI_Callback<void, std::shared_ptr<BMD::USB::IUSBDevice> >(Napi::Value, std::function<void (Napi::Env, std::vector<napi_value__*, std::allocator<napi_value__*> >&, std::shared_ptr<BMD::USB::IUSBDevice>)>, std::function<void (Napi::Env, Napi::Value)>)::{lambda(Napi::Env, Napi::Function, std::vector<napi_value__*, std::allocator<napi_value__*> > const&)#1}&, Napi::Env, Napi::Function, std::vector<napi_value__*, std::allocator<napi_value__*> > const&>(std::__invoke_other, SWIG_NAPI_Callback<void, std::shared_ptr<BMD::USB::IUSBDevice> >(Napi::Value, std::function<void (Napi::Env, std::vector<napi_value__*, std::allocator<napi_value__*> >&, std::shared_ptr<BMD::USB::IUSBDevice>)>, std::function<void (Napi::Env, Napi::Value)>)::{lambda(Napi::Env, Napi::Function, std::vector<napi_value__*, std::allocator<napi_value__*> > const&)#1}&, Napi::Env&&, Napi::Function&&, std::vector<napi_value__*, std::allocator<napi_value__*> > const&) (__f=..., __args=std::vector of length 1, capacity 1 = {...}, __args=std::vector of length 1, capacity 1 = {...}, __args=std::vector of length 1, capacity 1 = {...})
    at /usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:61
#5  0x00007ffff45b168c in std::__invoke_r<Napi::Value, SWIG_NAPI_Callback<void, std::shared_ptr<BMD::USB::IUSBDevice> >(Napi::Value, std::function<void (Napi::Env, std::vector<napi_value__*, std::allocator<napi_value__*> >&, std::shared_ptr<BMD::USB::IUSBDevice>)>, std::function<void (Napi::Env, Napi::Value)>)::{lambda(Napi::Env, Napi::Function, std::vector<napi_value__*, std::allocator<napi_value__*> > const&)#1}&, Napi::Env, Napi::Function, std::vector<napi_value__*, std::allocator<napi_value__*> > const&>(SWIG_NAPI_Callback<void, std::shared_ptr<BMD::USB::IUSBDevice> >(Napi::Value, std::function<void (Napi::Env, std::vector<napi_value__*, std::allocator<napi_value__*> >&, std::shared_ptr<BMD::USB::IUSBDevice>)>, std::function<void (Napi::Env, Napi::Value)>)::{lambda(Napi::Env, Napi::Function, std::vector<napi_value__*, std::allocator<napi_value__*> > const&)#1}&, Napi::Env&&, Napi::Function&&, std::vector<napi_value__*, std::allocator<napi_value__*> > const&) (__fn=..., __args=std::vector of length 1, capacity 1 = {...}, __args=std::vector of length 1, capacity 1 = {...}, __args=std::vector of length 1, capacity 1 = {...})
    at /usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:114
#6  0x00007ffff45b154c in std::_Function_handler<Napi::Value (Napi::Env, Napi::Function, std::vector<napi_value__*, std::allocator<napi_value__*> > const&), SWIG_NAPI_Callback<void, std::shared_ptr<BMD::USB::IUSBDevice> >(Napi::Value, std::function<void (Napi::Env, std::vector<napi_value__*, std::allocator<napi_value__*> >&, std::shared_ptr<BMD::USB::IUSBDevice>)>, std::function<void (Napi::Env, Napi::Value)>)::{lambda(Napi::Env, Napi::Function, std::vector<napi_value__*, std::allocator<napi_value__*> > const&)#1}>::_M_invoke(std::_Any_data const&, Napi::Env&&, Napi::Function&&, std::vector<napi_value__*, std::allocator<napi_value__*> > const&) (__functor=..., __args=std::vector of length 1, capacity 1 = {...}, __args=std::vector of length 1, capacity 1 = {...}, __args=std::vector of length 1, capacity 1 = {...}) at /usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_function.h:290
#7  0x00007ffff45b00ef in std::function<Napi::Value (Napi::Env, Napi::Function, std::vector<napi_value__*, std::allocator<napi_value__*> > const&)>::operator()(Napi::Env, Napi::Function, std::vector<napi_value__*, std::allocator<napi_value__*> > const&) const (this=0x7fffffff8650, 
    __args=std::vector of length 1, capacity 1 = {...}, __args=std::vector of length 1, capacity 1 = {...}, __args=std::vector of length 1, capacity 1 = {...}) at /usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_function.h:590
#8  0x00007ffff45af93d in SWIG_NAPI_Callback<void, std::shared_ptr<BMD::USB::IUSBDevice> >(Napi::Value, std::function<void (Napi::Env, std::vector<napi_value__*, std::allocator<napi_value__*> >&, std::shared_ptr<BMD::USB::IUSBDevice>)>, std::function<void (Napi::Env, Napi::Value)>, std::function<Napi::Value (Napi::Env, Napi::Function, std::vector<napi_value__*, std::allocator<napi_value__*> > const&)>)::{lambda(std::shared_ptr<BMD::USB::IUSBDevice>&&)#1}::operator()(std::shared_ptr<BMD::USB::IUSBDevice>&&) const::{lambda(Napi::Env, Napi::Function)#1}::operator()(Napi::Env, Napi::Function) const (
    this=0x7fffffff85c8, env=..., js_fn=...) at CMakeFiles/rpc.dir/rpcJAVASCRIPT_wrap.cxx:1444
#9  0x00007ffff45af58e in SWIG_NAPI_Callback<void, std::shared_ptr<BMD::USB::IUSBDevice> >(Napi::Value, std::function<void (Napi::Env, std::vector<napi_value__*, std::allocator<napi_value__*> >&, std::shared_ptr<BMD::USB::IUSBDevice>)>, std::function<void (Napi::Env, Napi::Value)>, std::function<Napi::Value (Napi::Env, Napi::Function, std::vector<napi_value__*, std::allocator<napi_value__*> > const&)>)::{lambda(std::shared_ptr<BMD::USB::IUSBDevice>&&)#1}::operator()(std::shared_ptr<BMD::USB::IUSBDevice>&&) const (this=0x5884230, args=...) at CMakeFiles/rpc.dir/rpcJAVASCRIPT_wrap.cxx:1510
#10 0x00007ffff45af362 in std::__invoke_impl<void, SWIG_NAPI_Callback<void, std::shared_ptr<BMD::USB::IUSBDevice> >(Napi::Value, std::function<void (Napi::Env, std::vector<napi_value__*, std::allocator<napi_value__*> >&, std::shared_ptr<BMD::USB::IUSBDevice>)>, std::function<void (Napi::Env, Napi::Value)>, std::function<Napi::Value (Napi::Env, Napi::Function, std::vector<napi_value__*, std::allocator<napi_value__*> > const&)>)::{lambda(std::shared_ptr<BMD::USB::IUSBDevice>&&)#1}&, std::shared_ptr<BMD::USB::IUSBDevice> >(std::__invoke_other, SWIG_NAPI_Callback<void, std::shared_ptr<BMD::USB::IUSBDevice> >(Napi::Value, std::function<void (Napi::Env, std::vector<napi_value__*, std::allocator<napi_value__*> >&, std::shared_ptr<BMD::USB::IUSBDevice>)>, std::function<void (Napi::Env, Napi::Value)>, std::function<Napi::Value (Napi::Env, Napi::Function, std::vector<napi_value__*, std::allocator<napi_value__*> > const&)>)::{lambda(std::shared_ptr<BMD::USB::IUSBDevice>&&)#1}&, std::shared_ptr<BMD::USB::IUSBDevice>&&) (__f=..., __args=...) at /usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:61
#11 0x00007ffff45af2f2 in std::__invoke_r<void, SWIG_NAPI_Callback<void, std::shared_ptr<BMD::USB::IUSBDevice> >(Napi::Value, std::function<void (Napi::Env, std::vector<napi_value__*, std::allocator<napi_value__*> >&, std::shared_ptr<BMD::USB::IUSBDevice>)>, std::function<void (Napi::Env, Napi::Value)>, std::function<Napi::Value (Napi::Env, Napi::Function, std::vector<napi_value__*, std::allocator<napi_value__*> > const&)>)::{lambda(std::shared_ptr<BMD::USB::IUSBDevice>&&)#1}&, std::shared_ptr<BMD::USB::IUSBDevice> >(SWIG_NAPI_Callback<void, std::shared_ptr<BMD::USB::IUSBDevice> >(Napi::Value, std::function<void (Napi::Env, std::vector<napi_value__*, std::allocator<napi_value__*> >&, std::shared_ptr<BMD::USB::IUSBDevice>)>, std::function<void (Napi::Env, Napi::Value)>, std::function<Napi::Value (Napi::Env, Napi::Function, std::vector<napi_value__*, std::allocator<napi_value__*> > const&)>)::{lambda(std::shared_ptr<BMD::USB::IUSBDevice>&&)#1}&, std::shared_ptr<BMD::USB::IUSBDevice>&&) (__fn=..., __args=...) at /usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/invoke.h:111
#12 0x00007ffff45aee22 in std::_Function_handler<void (std::shared_ptr<BMD::USB::IUSBDevice>), SWIG_NAPI_Callback<void, std::shared_ptr<BMD::USB::IUSBDevice> >(Napi::Value, std::function<void (Napi::Env, std::vector<napi_value__*, std::allocator<napi_value__*> >&, std::shared_ptr<BMD::USB::IUSBDevice>)>, std::function<void (Napi::Env, Napi::Value)>, std::function<Napi::Value (Napi::Env, Napi::Function, std::vector<napi_value__*, std::allocator<napi_value__*> > const&)>)::{lambda(std::shared_ptr<BMD::USB::IUSBDevice>&&)#1}>::_M_invoke(std::_Any_data const&, std::shared_ptr<BMD::USB::IUSBDevice>&&) (
    __functor=..., __args=...) at /usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_function.h:290
#13 0x00007ffff46ba685 in std::function<void (std::shared_ptr<BMD::USB::IUSBDevice>)>::operator()(std::shared_ptr<BMD::USB::IUSBDevice>) const (this=0x5884108, __args=warning: RTTI symbol not found for class 'std::_Sp_counted_deleter<BMD::USB::IUSBDevice*, std::_Mem_fn<int (BMD::USB::IUSBDevice::*)()>, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
warning: RTTI symbol not found for class 'std::_Sp_counted_deleter<BMD::USB::IUSBDevice*, std::_Mem_fn<int (BMD::USB::IUSBDevice::*)()>, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>'
std::shared_ptr<BMD::USB::IUSBDevice> (use count 3, weak count 0) = {...})
    at /usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/bits/std_function.h:590
#14 0x00007ffff46b9e02 in BlamOSRPC::UsbNotifier::onDeviceAdded (this=0x58840a0, usbDevice=0x5a66730) at /home/build/build/bmd-eng-ub_d0aV/project/BlackmagicTools/AppiumDriver/src/UsbNotifier.cpp:38
#15 0x00007ffff46d03ea in BasicUSBNotifier::deviceAddedNotification (this=0x58840a8, usbDevice=0x5a66730) at /home/build/build/bmd-eng-ub_vDna/project/src/lib/common/BasicUSBNotifier.cpp:137
#16 0x00007ffff46d07b0 in BasicUSBNotifier::deviceAddedNotificationCb (usbDevice=0x5a66730, refCon=0x58840a8) at /home/build/build/bmd-eng-ub_vDna/project/src/lib/common/BasicUSBNotifier.hpp:55
#17 0x00007ffff46d3bf4 in BMD::USB::BMDUsb_InstallDeviceNotification (arrivalCallback=0x7ffff46d0790 <BasicUSBNotifier::deviceAddedNotificationCb(BMD::USB::IUSBDevice*, void*)>, arrivalRefCon=0x58840a8, 
    removalCallback=0x7ffff46d07c0 <BasicUSBNotifier::deviceRemovedNotificationCb(BMD::USB::IUSBDevice*, void*)>, removalRefCon=0x58840a8, deviceMatch=0x7fffffff8a08) at /home/build/build/bmd-eng-ub_vDna/project/src/lib/linux/LibBMDUsb.cpp:515
#18 0x00007ffff46d0365 in BasicUSBNotifier::startNotifications (this=0x58840a8) at /home/build/build/bmd-eng-ub_vDna/project/src/lib/common/BasicUSBNotifier.cpp:67
#19 0x00007ffff46ba17d in BlamOSRPC::UsbNotifier::init (this=0x58840a0) at /home/build/build/bmd-eng-ub_d0aV/project/BlackmagicTools/AppiumDriver/src/UsbNotifier.cpp:194
#20 0x00007ffff452892f in _exports_UsbNotifier_templ<_exports_UsbNotifier_inst>::_wrap_UsbNotifier_init (this=0x7fffcc011e40, info=...) at CMakeFiles/rpc.dir/rpcJAVASCRIPT_wrap.cxx:26362
#21 0x00007ffff45aad7a in Napi::InstanceWrap<_exports_UsbNotifier_inst>::InstanceMethodCallbackWrapper(napi_env__*, napi_callback_info__*)::{lambda()#1}::operator()() const (this=0x7fffffff8d38)
    at /home/build/build/bmd-eng-ub_d0aV/project/BlackmagicTools/AppiumDriver/node_modules/node-addon-api/napi-inl.h:4531
#22 0x00007ffff45aaad9 in Napi::details::WrapCallback<Napi::InstanceWrap<_exports_UsbNotifier_inst>::InstanceMethodCallbackWrapper(napi_env__*, napi_callback_info__*)::{lambda()#1}>(Napi::InstanceWrap<_exports_UsbNotifier_inst>::InstanceMethodCallbackWrapper(napi_env__*, napi_callback_info__*)::{lambda()#1}) (callback=...) at /home/build/build/bmd-eng-ub_d0aV/project/BlackmagicTools/AppiumDriver/node_modules/node-addon-api/napi-inl.h:85
#23 0x00007ffff45aa5bd in Napi::InstanceWrap<_exports_UsbNotifier_inst>::InstanceMethodCallbackWrapper (env=0x5789270, info=0x7fffffff8d90) at /home/build/build/bmd-eng-ub_d0aV/project/BlackmagicTools/AppiumDriver/node_modules/node-addon-api/napi-inl.h:4524
#24 0x0000000000c5c525 in v8impl::(anonymous namespace)::FunctionCallbackWrapper::Invoke(v8::FunctionCallbackInfo<v8::Value> const&) ()
#25 0x0000000000f6e88f in v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) ()
#26 0x0000000000f6f0fd in v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, unsigned long*, int) ()
#27 0x0000000000f6f5c5 in v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) ()
#28 0x0000000001979df6 in Builtins_CEntry_Return1_ArgvOnStack_BuiltinExit ()
#29 0x00000000018ebd1c in Builtins_InterpreterEntryTrampoline ()
```

**Comment by mateusz-plociennik** [comment]
No, I can’t provide a full reproduction. However, I will try to create a minimal reproducible example.
